// Autogenerated from Pigeon (v22.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by all APIs.
NSObject<FlutterMessageCodec> *GetAgeSdkCodec(void);

@protocol AgeSdkApi
- (void)getAgeWithCompletion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
@end

extern void SetUpAgeSdkApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<AgeSdkApi> *_Nullable api);

extern void SetUpAgeSdkApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<AgeSdkApi> *_Nullable api, NSString *messageChannelSuffix);

NS_ASSUME_NONNULL_END
